language: ruby
cache: bundler
rvm: 2.6

# 缓存，可以节省集成的时间
cache:
  apt: true
  gem: true
  directories:
    - node_modules
    
before_install:
  - git config --global user.name "KevinsBobo"
  - git config --global user.email "kevins.bobo@gmail.com"
  - export TZ='Asia/Shanghai'
  - chmod a+x _travis.sh
  - chmod a+x script/bootstrap
  - chmod a+x script/cibuild
  - chmod a+x script/release
  - chmod a+x script/server
  - chmod a+x script/validate-html
install: script/bootstrap
script: script/cibuild
after_success:
  - ./_travis.sh

env:
  global:
    # 修改为自己Github用户名
    - GH_USER_NAME: KevinsBobo
    # 修改为自己Github仓库地址
    - GH_REF: github.com/KevinsBobo/KevinsBobo.github.io.git
    # 修改为自己Coding用户名
    - CODING_USER_NAME: sport
    # 修改为自己Coding仓库地址
    - CODING_REF: e.coding.net/KevinsBobo/KevinsBobo.coding.me.git

