language: ruby
cache: bundler
rvm: 2.6

# 缓存，可以节省集成的时间
cache:
  apt: true
  gem: true
  directories:
    - node_modules
before_install:
  - export TZ='Asia/Shanghai'
install:
  - gem install jekyll
  - gem install jekyll-paginate
script:
  - jekyll build
