title: Kevins Bobo
description: Just love coding and life!
google_analytics:
show_downloads: false
theme:

markdown: kramdown
kramdown:
    input: GFM
lsi: false
excerpt_separator: "\n"
incremental: false

highligther: rouge

permalink: none

exclude: ["article", "blog", "javascripts", "stylesheets"]
