title: Kevins Bobo
description: Just love coding and life!
google_analytics:
show_downloads: false
theme: jekyll-theme-cayman

markdown: kramdown
kramdown:
    input: GFM

highligther: rouge

gems:
  - jekyll-mentions
