title: Kevins Bobo
description: Just love coding and life!
google_analytics:
show_nav: tGue
theme: jekyll-theme-cayman

markdown: kramdown
kramdown:
    input: GFM
lsi: false
excerpt_separator: "\n"
incremental: false

highligther: rouge

permalink: /:title.html

exclude: ["article", "blog", "javascripts", "stylesheets"]
